<a href="https://colab.research.google.com/github/Harsh-eng568/IMBD-analysis/blob/main/imdb1000_pandas_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [5]:
movies = pd.read_csv('/content/imdb-top-1000.csv')
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [6]:
genres = movies.groupby('Genre')

In [7]:
# find top 3 genres by total earning
movies.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [8]:
# find the genre with highest average rating
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(5)

Genre
Western      8.350000
Crime        8.016822
Fantasy      8.000000
Mystery      7.975000
Film-Noir    7.966667
Name: IMDB_Rating, dtype: float64

In [9]:
# find the director with most popularity
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False).head(5)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
David Fincher         6607859
Martin Scorsese       6513530
Name: No_of_Votes, dtype: int64

In [10]:
# find the highest rated movie in each genre
movies.groupby('Genre')['IMDB_Rating'].max().sort_values(ascending=False).head(5)

Genre
Drama        9.3
Crime        9.2
Action       9.0
Biography    8.9
Western      8.8
Name: IMDB_Rating, dtype: float64

In [11]:
# find the number of movies done by each actor
movies.groupby('Star1')['Series_Title'].count().sort_values(ascending=False)

Star1
Tom Hanks             12
Robert De Niro        11
Clint Eastwood        10
Al Pacino             10
Leonardo DiCaprio      9
                      ..
Glen Hansard           1
Giuseppe Battiston     1
Giulietta Masina       1
Gerardo Taracena       1
Ömer Faruk Sorak       1
Name: Series_Title, Length: 660, dtype: int64

In [12]:
movies.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [13]:
genre = movies.groupby('Genre')
genre.nth(6)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [14]:
genre.get_group('Horror')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [15]:
genre.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [16]:
  genre.agg(
      {
          'Runtime':'mean',
          'No_of_Votes':'sum',
          'Gross': 'sum',
          'IMDB_Rating': 'mean'
      }
  )

              Runtime  No_of_Votes         Gross  IMDB_Rating
Genre
Action     129.046512     72282412  3.263226e+10     7.949419
Adventure  134.111111     22576163  9.496922e+09     7.937500
Animation   99.585366     21978630  1.463147e+10     7.930488
Biography  136.022727     24006844  8.276358e+09     7.938636
Comedy     112.129032     27620327  1.566387e+10     7.901290
Crime      126.392523     33533615  8.452632e+09     8.016822
Drama      124.737024     61367304  3.540997e+10     7.957439
Family     107.500000       551221  4.391106e+08     7.800000
Fantasy     85.000000       146222  7.827267e+08     8.000000
Film-Noir  104.000000       367215  1.259105e+08     7.966667
Horror     102.090909      3742556  1.034649e+09     7.909091
Mystery    119.083333      4203004  1.256417e+09     7.975000
Thriller   108.000000        27733  1.755074e+07     7.800000
Western    148.250000      1289665  5.822151e+07     8.350000

In [17]:
df = pd.DataFrame(columns = movies.columns)
for group, data in genre:
  df = pd.concat([df, data[data['IMDB_Rating'] == data['IMDB_Rating'].max()]], ignore_index=True)
df

<ipython-input-17-b8ebcdd5bcb6>:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, data[data['IMDB_Rating'] == data['IMDB_Rating'].max()]], ignore_index=True)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
1,Interstellar,2014,169,Adventure,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
2,Sen to Chihiro no kamikakushi,2001,125,Animation,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
3,Schindler's List,1993,195,Biography,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
4,Gisaengchung,2019,132,Comedy,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
5,La vita è bella,1997,116,Comedy,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
6,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
7,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
8,E.T. the Extra-Terrestrial,1982,115,Family,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
9,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
10,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
11,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
12,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
13,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
14,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
15,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
16,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [19]:
# find the number of movies starting with A for each group
def foo(group):
   group['Series_Title'].str.startswith('A')
   return group

In [20]:
genre.apply(foo)

<ipython-input-20-ee52bd31eb48>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(foo)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

[1000 rows x 10 columns]

In [21]:
# find ranking of each movie in the group according to IMBD score

def rank_movie(group):
  group['genre_rank'] = group['IMDB_Rating'].rank(ascending=False)
  return group

In [22]:
genre.apply(rank_movie)

<ipython-input-22-d537fca52807>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(rank_movie)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              genre_rank
Genre
Action   2           1.0
         5           2.0
         8           3.5
         10          3.5
         13          6.0
...                  ...
Thriller 700         1.0
Western  12          1.0
         48          2.0
         115         3.0
         691         4.0

[1000 rows x 11 columns]

In [23]:
# find normalized IMBD rating group wise
def normalize_rating(group):
  group['normalized_rating'] = (group['IMDB_Rating'] - group['IMDB_Rating'].min()) / (group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
  return group

In [24]:
genre.apply(normalize_rating)

<ipython-input-24-53a4bd3374e3>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(normalize_rating)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              normalized_rating
Genre
Action   2             1.000000
         5             0.928571
         8             0.857143
         10            0.857143
         13            0.785714
...                         ...
Thriller 700                NaN
Western  12            1.000000
         48            0.700000
         115           0.500000
         691           0.000000

[1000 rows x 11 columns]

In [25]:
# find the most earning actor
duo = movies.groupby(['Director', 'Star1'])
duo['Gross'].sum().sort_values(ascending=False).head(5)

Director           Star1
Akira Kurosawa     Toshirô Mifune    2.999877e+09
Anthony Russo      Joe Russo         2.205039e+09
Billy Wilder       William Holden    1.286779e+09
Christopher Nolan  Christian Bale    1.242940e+09
Werner Herzog      Klaus Kinski      1.124605e+09
Name: Gross, dtype: float64